services:
  ollama:
    image: "docker.io/ollama/ollama"
    ports:
      - "11434:11434"
    volumes:
      - ~/ollama-storage:/root/.ollama
    entrypoint: ["/usr/bin/bash", "-c", "/bin/ollama serve & sleep 5; ollama pull deepseek-r1:1.5b; wait"]

  "sapphire-localnet":
    image: "ghcr.io/oasisprotocol/sapphire-localnet"
    platform: "linux/x86_64"
    ports:
      - "8544-8548:8544-8548"
    healthcheck:
      test: ["CMD", "test", "-f", "/CONTAINER_READY"]
      interval: 30s
      timeout: 10s
      retries: 20

  contracts:
    image: "ghcr.io/foundry-rs/foundry:latest"
    volumes:
      - ./contracts:/contracts
    entrypoint: /bin/sh -c 'cd contracts && forge create --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://sapphire-localnet:8545 --broadcast ChatBot --constructor-args localhost 00d795c033fb4b94873d81b6327f5371768ffc6fcf 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    depends_on:
      "sapphire-localnet":
        condition: service_healthy

  oracle:
    environment:
      CONTRACT_ADDRESS: 0x5FbDB2315678afecb367f032d93F642f64180aa3
    build:
      dockerfile: Dockerfile.oracle
        #    entrypoint: /bin/sh -c 'python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 $${CONTRACT_ADDRESS}'
    entrypoint: /bin/sh -c 'sleep 100; python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0x5FbDB2315678afecb367f032d93F642f64180aa3'
    restart: on-failure
    depends_on:
      contracts:
        condition: service_completed_successfully

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      contracts:
        condition: service_completed_successfully
